#!/bin/sh

# This file was generated by the Jython installer
# Created on Thu Feb 22 18:12:39 CET 2007 by sergei

JYTHON_HOME="../../../lib/jython"

CP=${JYTHON_HOME}"/jython.jar"
if [ ! -z "$CLASSPATH" ]
then
  CP=$CP:$CLASSPATH
fi
java -Dpython.home="$JYTHON_HOME" -classpath "$CP" org.python.util.jython py2html.py -footer:footer.html  "$@"
# java -Dpython.home="$JYTHON_HOME" -classpath "$CP" org.python.util.jython "$@"
